language: java

jdk:
    - oraclejdk8

branches:
    except:
        - latest-master
        
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install oracle-java8-installer
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
        
install:
    - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes jq; fi

after_success:
    - chmod -R 777 ./upload_binaries.sh
    - ./upload_binaries.sh
    - mvn clean cobertura:cobertura coveralls:cobertura
    
env:
    global:
        secure: "K+vew/JP2/aPnR6YpHQDEnLkY8vfFHRcF/Xm//6q5xTTjvZnRZlJSN8e8aE8ohQFiDClJbIETK0x1v9f/dmWUKxD6QmrNJh5LwErTcmUhVGXooR4ImY/5JBVLeMLq4mLqD61O3dJeo7zzOHHCXD9mTaj0bDySGBdA/hoOVpPFBw="